NOM = "GROSMAIRE"
Prenom = "Arthur"
Classe = "MPSI2"
alpha="71"

## Question 1
Q1_req = "SELECT CLI_NOM,CLI_PRENOM,TIT_CODE FROM T_CLIENT;"

## Question 2
Q2_req = "SELECT COUNT(*) FROM T_CLIENT;"
Q2_res = "88"

## Question 3
Q3_req = "SELECT CLI_NOM,CLI_PRENOM FROM T_CLIENT WHERE TIT_CODE='Mme.';"

## Question 4
Q4_req = "SELECT CLI_NOM,CLI_PRENOM,TIT_CODE FROM T_CLIENT WHERE TIT_CODE='Mme.' UNION SELECT CLI_NOM,CLI_PRENOM,TIT_CODE FROM T_CLIENT WHERE TIT_CODE='Melle.';"


## Question 5
Q5_req = "SELECT COUNT(*) AS CLI_ID FROM T_CLIENT WHERE TIT_CODE='Mme.' OR TIT_CODE='Melle.';"
Q5_res = "16"

## Question 6
Q6_req = "SELECT CLI_NOM AS Noms,CLI_PRENOM AS Prenoms FROM T_CLIENT  WHERE TIT_CODE='Mme.' OR TIT_CODE='Melle.' ORDER BY CLI_NOM asc, CLI_PRENOM asc;"


## Question 7
Q7_req = "SELECT CLI_NOM,TEL_NUMERO FROM T_CLIENT JOIN T_TELEPHONE;"

## Question 8
Q8_req = "SELECT CLI_NOM,CLI_PRENOM FROM T_CLIENT GROUP BY CLI_NOM HAVING COUNT(CLI_NOM)>1;"

## Question 9
Q9_req = "SELECT COUNT(*) FROM T_CLIENT GROUP BY CLI_NOM HAVING COUNT(CLI_NOM)>1;"
Q9_res = "2"

## Question 10
Q10_req = "SELECT AVG(LIF_REMISE_POURCENT) FROM T_LIGNE_FACTURE UNION SELECT AVG(LIF_REMISE_MONTANT) FROM T_LIGNE_FACTURE;"
Q10_res = "86% et 120"

## Question 11
Q11_req = "SELECT MAX(LIF_REMISE_POURCENT) FROM T_LIGNE_FACTURE UNION SELECT MAX(LIF_REMISE_MONTANT) FROM T_LIGNE_FACTURE;"
Q11_res = "86% et 120"

## Question 12
Q12_req = "SELECT FAC_ID AS fac_id1 FROM T_LIGNE_FACTURE WHERE LIF_REMISE_MONTANT>=0 OR LIF_REMISE_POURCENT>=0;"


## Question 13
Q13_req = "SELECT CLI_ID FROM T_FACTURE JOIN T_LIGNE_FACTURE WHERE LIF_REMISE_MONTANT>=0 OR LIF_REMISE_POURCENT>=0;"

## Question 14
Q14_req = "SELECT CLI_ID FROM T_FACTURE JOIN T_LIGNE_FACTURE WHERE LIF_REMISE_MONTANT=NULL OR LIF_REMISE_POURCENT=NULL;"


## Question 15
Q15_req = ""
Q15_res ="Aucun client n'a eu une remise plus importante que les autres, vu que il n'y a qu'une remise de 86% ou de 120 euros"
