NOM = "DEBONO"
Prenom = "Juliette"
Classe = "MPSI 2"
alpha="5"

## Question 1
Q1_req = "SELECT CLI_NOM, CLI_PRENOM, TIT_CODE FROM T_CLIENT;"

## Question 2
Q2_req = "SELECT COUNT(*) FROM T_CLIENT;"
Q2_res = "99"

## Question 3
Q3_req = "SELECT CLI_NOM, CLI_PRENOM FROM T_CLIENT WHERE TIT_CODE = 'Mme.'"

## Question 4
Q4_req = "SELECT CLI_NOM, CLI_PRENOM, TIT_CODE FROM T_CLIENT WHERE TIT_CODE != 'M.'"


## Question 5
Q5_req = "SELECT COUNT(*) FROM T_CLIENT WHERE TIT_CODE != 'M.'"
Q5_res = "16"

## Question 6
Q6_req = "SELECT CLI_NOM AS 'Noms', CLI_PRENOM AS 'Prénons' FROM T_CLIENT WHERE TIT_CODE != 'M.' ORDER BY CLI_NOM, CLI_PRENOM;"


## Question 7
Q7_req = "SELECT CLI_NOM, TEL_NUMERO FROM T_CLIENT, T_TELEPHONE WHERE T_CLIENT.CLI_ID = T_TELEPHONE.CLI_ID;"

## Question 8
Q8_req = "SELECT * FROM T_CLIENT WHERE CLI_NOM IN (SELECT CLI_NOM FROM T_CLIENT GROUP BY CLI_NOM HAVING COUNT(CLI_NOM) > 1);"

## Question 9
Q9_req = "SELECT CLI_NOM, count(CLI_NOM) FROM T_CLIENT GROUP BY CLI_NOM HAVING COUNT(CLI_NOM) > 1;"
Q9_res = "BENATTAR 2 MARTIN 3"

## Question 10
Q10_req = "SELECT AVG(LIF_REMISE_POURCENT) as 'Moyenne pourcent', AVG(LIF_REMISE_MONTANT) as 'Moyenne montant' FROM T_LIGNE_FACTURE;"
Q10_res = "20.0 54.0"

## Question 11
Q11_req = "SELECT Max(LIF_REMISE_POURCENT) as 'Max pourcent', Max(LIF_REMISE_MONTANT) as 'Max montant' FROM T_LIGNE_FACTURE;"
Q11_res = "20 54"

## Question 12
Q12_req = "SELECT DISTINCT FAC_ID AS 'fac_id1' FROM T_LIGNE_FACTURE WHERE LIF_REMISE_POURCENT NOT NULL OR LIF_REMISE_MONTANT NOT NULL;"


## Question 13
Q13_req = "SELECT DISTINCT CLI_ID FROM T_FACTURE, T_LIGNE_FACTURE WHERE LIF_REMISE_POURCENT NOT NULL OR LIF_REMISE_MONTANT NOT NULL;"

## Question 14
Q14_req = "SELECT DISTINCT CLI_ID FROM T_FACTURE, T_LIGNE_FACTURE WHERE LIF_REMISE_POURCENT IS NULL AND LIF_REMISE_MONTANT IS NULL;"


## Question 15
Q15_req = ""
Q15_res ="nom,prenom,montant"
