NOM = "MOSTEFAOUI"
Prenom = "Rayan"
Classe = "MPSI2"
alpha="67"

## Question 1
Q1_req = "SELECT TIT_CODE,CLI_NOM,CLI_PRENOM FROM T_CLIENT;"

## Question 2
Q2_req = "SELECT COUNT(*) as nbclients FROM T_CLIENT;"
Q2_res = "89"

## Question 3
Q3_req = "SELECT CLI_NOM,CLI_PRENOM FROM T_CLIENT WHERE TIT_CODE='Mme.';"

## Question 4
Q4_req = "SELECT TIT_CODE,CLI_NOM,CLI_PRENOM FROM T_CLIENT WHERE TIT_CODE='Mme.' OR TIT_CODE='Melle.';"


## Question 5
Q5_req = "SELECT COUNT(*) as nbclientes FROM (SELECT TIT_CODE,CLI_NOM,CLI_PRENOM FROM T_CLIENT WHERE TIT_CODE='Mme.' OR TIT_CODE='Melle.');"
Q5_res = "17"

## Question 6
Q6_req = "SELECT CLI_NOM as Noms, CLI_PRENOM as Prénoms FROM (SELECT TIT_CODE,CLI_NOM,CLI_PRENOM FROM T_CLIENT WHERE TIT_CODE='Mme.' OR TIT_CODE='Melle.') ORDER BY Noms ASC, Prénoms ASC;"


## Question 7
Q7_req = "CREATE TABLE CLI_TEL AS SELECT T_CLIENT.CLI_NOM,T_TELEPHONE.TEL_NUMERO,T_TELEPHONE.TEL_LOCALISATION FROM T_CLIENT,T_TELEPHONE WHERE TYP_CODE='TEL' AND T_CLIENT.CLI_ID=T_TELEPHONE.CLI_ID;"

## Question 8
Q8_req = "SELECT CLI_NOM, as nb_occ FROM T_CLIENT WHERE COUNT(CLI_NOM) > 1;"

## Question 9
Q9_req = "SELECT CLI_NOM, COUNT(*) as nb_occ FROM T_CLIENT GROUP BY CLI_NOM HAVING nb_occ > 1;"
Q9_res = "MARTIN,2"

## Question 10
Q10_req = "SELECT AVG(LIF_REMISE_POURCENT) as moyenne_remise,AVG(LIF_REMISE_MONTANT) as moyenne_montant FROM T_LIGNE_FACTURE;"
Q10_res = "82.0,116.0"

## Question 11
Q11_req = "SELECT MAX(LIF_REMISE_POURCENT) as moyenne_remise,MAX(LIF_REMISE_MONTANT) as moyenne_montant FROM T_LIGNE_FACTURE;"
Q11_res = "82,116"

## Question 12
Q12_req = "SELECT DISTINCT T_LIGNE_FACTURE.FAC_ID as fac_id1 FROM T_LIGNE_FACTURE WHERE LIF_REMISE_MONTANT  NOTNULL OR LIF_REMISE_POURCENT NOTNULL;"


## Question 13
Q13_req = "SELECT DISTINCT T_FACTURE.CLI_ID FROM T_FACTURE JOIN T_LIGNE_FACTURE ON T_FACTURE.FAC_ID=T_LIGNE_FACTURE.FAC_ID WHERE LIF_REMISE_MONTANT NOTNULL OR LIF_REMISE_POURCENT NOTNULL;"

## Question 14
Q14_req = "SELECT T_FACTURE.CLI_ID FROM T_FACTURE EXCEPT SELECT DISTINCT T_FACTURE.CLI_ID FROM T_FACTURE JOIN T_LIGNE_FACTURE ON T_FACTURE.FAC_ID=T_LIGNE_FACTURE.FAC_ID WHERE LIF_REMISE_MONTANT NOTNULL OR LIF_REMISE_POURCENT NOTNULL;"


## Question 15
Q15_req = ""
Q15_res ="nom,prenom,montant"
