NOM = "GRAS"
Prenom = "Romain"
Classe = "MPSI2"
alpha="30"

## Question 1
Q1_req = "SELECT CLI_NOM,CLI_PRENOM,TIT_CODE FROM T_CLIENT"

## Question 2
Q2_req = "SELECT Count(*) FROM T_CLIENT"
Q2_res = "93"

## Question 3
Q3_req = "SELECT CLI_NOM,CLI_PRENOM,TIT_CODE FROM T_CLIENT WHERE TIT_CODE="Mme.""

## Question 4
Q4_req = "SELECT CLI_NOM,CLI_PRENOM,TIT_CODE FROM T_CLIENT WHERE TIT_CODE="Mme." OR TIT_CODE="Melle.""


## Question 5
Q5_req = "SELECT Count(*) FROM T_CLIENT WHERE TIT_CODE="Mme." OR TIT_CODE="Melle.""
Q5_res = "16"

## Question 6
Q6_req = "SELECT CLI_NOM AS Noms, CLI_PRENOM AS Prénoms FROM T_CLIENT WHERE TIT_CODE="Mme." OR TIT_CODE="Melle." ORDER BY Noms, Prénoms"


## Question 7
Q7_req = "SELECT CLI_NOM, TEL_NUMERO FROM T_TELEPHONE, T_CLIENT WHERE T_TELEPHONE.CLI_ID=T_CLIENT.CLI_ID"

## Question 8
Q8_req = ""

## Question 9
Q9_req = "SELECT COUNT(CLI_NOM), CLI_NOM FROM T_CLIENT GROUP BY CLI_NOM"
Q9_res = ""

## Question 10
Q10_req = "SELECT AVG(LIF_REMISE_MONTANT), AVG(LIF_REMISE_POURCENT) FROM T_LIGNE_FACTURE;"
Q10_res = "79.0	45.0"

## Question 11
Q11_req = "SELECT MAX(LIF_REMISE_MONTANT), MAX(LIF_REMISE_POURCENT) FROM T_LIGNE_FACTURE;"
Q11_res = "79	45"

## Question 12
Q12_req = "SELECT FAC_ID AS fac_id1 FROM T_LIGNE_FACTURE WHERE LIF_REMISE_POURCENT != "NULL" OR LIF_REMISE_MONTANT IS NOT NULL"


## Question 13
Q13_req = "SELECT DISTINCT T_FACTURE.CLI_ID FROM T_LIGNE_FACTURE, T_FACTURE WHERE (LIF_REMISE_POURCENT IS NOT NULL OR LIF_REMISE_MONTANT IS NOT NULL) AND T_LIGNE_FACTURE.FAC_ID= T_FACTURE.FAC_ID;"

## Question 14
Q14_req = "SELECT CLI_ID FROM T_CLIENT EXCEPT SELECT CLI_ID FROM T_LIGNE_FACTURE, T_CLIENT WHERE (LIF_REMISE_POURCENT != "NULL" OR LIF_REMISE_MONTANT != "NULL") AND T_LIGNE_FACTURE.LIF_ID= T_CLIENT.CLI_ID"


## Question 15
Q15_req = ""
Q15_res ="nom,prenom,montant"
