NOM = "TOUILEB"
Prenom = "Laura"
Classe = "MPSI2"
alpha="78"

## Question 1
Q1_req = "SELECT CLI_NOM, CLI_PRENOM,TIT_CODE FROM T_CLIENT;"

## Question 2
Q2_req = "SELECT COUNT (*) FROM T_CLIENT;"
Q2_res = "87"

## Question 3 

Q3_req = "SELECT CLI_NOM,CLI_PRENOM FROM T_CLIENT WHERE TIT_CODE ='Mme.';"

## Question 4
Q4_req = "SELECT  CLI_NOM, CLI_PRENOM,TIT_CODE FROM T_CLIENT WHERE TIT_CODE = 'Mme.' OR TIT_CODE = 'Melle.';"


## Question 5
Q5_req = "SELECT COUNT(*) FROM (SELECT  CLI_NOM, CLI_PRENOM,TIT_CODE FROM T_CLIENT WHERE TIT_CODE = 'Mme.' OR TIT_CODE = 'Melle.');"
Q5_res = "16"

## Question 6
Q6_req = "SELECT CLI_NOM AS Noms, CLI_PRENOM AS Prénoms FROM (SELECT  CLI_NOM, CLI_PRENOM,TIT_CODE FROM T_CLIENT WHERE TIT_CODE = 'Mme.' OR TIT_CODE = 'Melle.') ORDER BY Noms;"


## Question 7
Q7_req = "SELECT T_CLIENT.CLI_NOM, T_TELEPHONE.TEL_NUMERO FROM T_CLIENT JOIN T_TELEPHONE ON T_CLIENT.CLI_ID = T_TELEPHONE.CLI_ID;"

## Question 8
Q8_req = "SELECT * FROM T_CLIENT WHERE CLI_NOM IN (SELECT CLI_NOM FROM T_CLIENT GROUP BY CLI_NOM HAVING COUNT(CLI_NOM) > 1);"

## Question 9
Q9_req = "SELECT COUNT(CLI_ID) FROM "
Q9_res = "2,2"

## Question 10
Q10_req = "SELECT AVG(LIF_REMISE_POURCENT), AVG(LIF_REMISE_MONTANT) FROM T_LIGNE_FACTURE;"
Q10_res = "93.0,127.0"

## Question 11
Q11_req = "SELECT max(LIF_REMISE_POURCENT), max(LIF_REMISE_MONTANT) FROM T_LIGNE_FACTURE;"
Q11_res = "93,127"

## Question 12
Q12_req = "SELECT FAC_ID AS fac_id1 FROM T_LIGNE_FACTURE WHERE LIF_REMISE_POURCENT NOT NULL OR LIF_REMISE_MONTANT NOT NULL;"


## Question 13 
Q13_req = "SELECT DISTINCT CLI_ID FROM T_FACTURE JOIN T_LIGNE_FACTURE ON T_LIGNE_FACTURE.FAC_ID = T_FACTURE.FAC_ID WHERE LIF_REMISE_POURCENT NOT NULL OR LIF_REMISE_MONTANT NOT NULL;"

## Question 14
Q14_req = "SELECT DISTINCT CLI_ID FROM T_FACTURE JOIN T_LIGNE_FACTURE ON T_LIGNE_FACTURE.FAC_ID = T_FACTURE.FAC_ID WHERE LIF_REMISE_POURCENT IS NULL AND LIF_REMISE_MONTANT IS NULL;"


## Question 15
Q15_req = ""
Q15_res ="nom,prenom,montant"
