NOM = "MARTINAL"
Prenom = "Lucie"
Classe = "MPSI2"
alpha="89"

## Question 1
Q1_req = "SELECT CLI_NOM, CLI_PRENOM, TIT_CODE FROM T_CLIENT"

## Question 2
Q2_req = "SELECT COUNT(*) FROM T_CLIENT"
Q2_res = "87"

## Question 3
Q3_req = "SELECT CLI_NOM, CLI_PRENOM FROM T_CLIENT WHERE TIT_CODE ='Mme.' "

## Question 4
Q4_req = "SELECT CLI_NOM, CLI_PRENOM, TIT_CODE FROM T_CLIENT WHERE TIT_CODE ='Mme.' OR TIT_CODE ='Melle.'"


## Question 5
Q5_req = "SELECT COUNT(*) FROM T_CLIENT WHERE TIT_CODE ='Mme.' OR TIT_CODE ='Melle.'"
Q5_res = "16"

## Question 6
Q6_req = "SELECT CLI_NOM AS 'Noms', CLI_PRENOM AS 'Prénoms' FROM T_CLIENT WHERE TIT_CODE = 'Mme.' OR TIT_CODE ='Melle.' ORDER BY CLI_NOM ASC, CLI_PRENOM ASC "


## Question 7
Q7_req = "SELECT CLI_NOM, TEL_NUMERO FROM T_CLIENT, T_TELEPHONE WHERE T_CLIENT.CLI_ID = T_TELEPHONE.CLI_ID"

## Question 8
Q8_req = "SELECT CLI_NOM, CLI_PRENOM FROM T_CLIENT GROUP BY CLI_NOM HAVING COUNT(CLI_NOM)>1 ;"

## Question 9
Q9_req = "SELECT CLI_NOM, COUNT(CLI_PRENOM) FROM T_CLIENT GROUP BY CLI_NOM"
Q9_res = " MARTIN : 2, BENATTAR :2"

## Question 10
Q10_req = "SELECT AVG(LIF_REMISE_POURCENT), AVG(LIF_REMISE_MONTANT) FROM T_LIGNE_FACTURE;"
Q10_res = "104 et 138"

## Question 11
Q11_req = "SELECT MAX(LIF_REMISE_POURCENT), MAX(LIF_REMISE_MONTANT) FROM T_LIGNE_FACTURE;"
Q11_res = "104 et 138"

## Question 12
Q12_req = "SELECT FAC_ID AS 'fac_id' FROM T_LIGNE_FACTURE WHERE (LIF_REMISE_MONTANT != NULL OR LIF_REMISE_POURCENT != NULL )"


## Question 13
Q13_req = "SELECT CLI_ID FROM T_CLIENT WHERE T_CLIENT.CLI_ID = ( SELECT CLI_ID FROM T_FACTURE WHERE T_FACTURE.FAC_ID = ( SELECT FAC_ID FROM T_LIGNE_FACTURE WHERE (LIF_REMISE_MONTANT = 138 OR LIF_REMISE_POURCENT = 104 )));"

## Question 14
Q14_req = "SELECT CLI_ID FROM T_CLIENT WHERE T_CLIENT.CLI_ID = ( SELECT CLI_ID FROM T_FACTURE WHERE T_FACTURE.FAC_ID = ( SELECT FAC_ID FROM T_LIGNE_FACTURE WHERE (LIF_REMISE_MONTANT != 138 AND LIF_REMISE_POURCENT != 104 )));"


## Question 15
Q15_req = ""
Q15_res ="nom,prenom,montant"
