NOM = "GREA"
Prenom = "Mattéo"
Classe = "MPSI2"
alpha="37"

## Question 1
Q1_req = "SELECT TIT_CODE, CLI_NOM, CLI_PRENOM FROM T_CLIENT "

## Question 2
Q2_req = "SELECT COUNT(*) FROM T_CLIENT"
Q2_res = "9"

## Question 3
Q3_req = "SELECT CLI_NOM, CLI_PRENOM FROM T_CLIENT WHERE TIT_CODE='Mme.'"

## Question 4
Q4_req = "SELECT TIT_CODE, CLI_NOM,CLI_PRENOM FROM T_CLIENT WHERE TIT_CODE='Mme.' OR TIT_CODE='Melle.'"


## Question 5
Q5_req = "SELECT COUNT(*) FROM T_CLIENT WHERE TIT_CODE='Mme.' OR TIT_CODE='Melle.'"
Q5_res = "17"

## Question 6
Q6_req = "SELECT CLI_NOM, CLI_PRENOM FROM T_CLIENT WHERE TIT_CODE='Mme.' OR TIT_CODE='Melle.' ORDER BY CLI_NOM,CLI_PRENOM ASC"


## Question 7
Q7_req = "SELECT CLI_NOM, TEL_NUMERO FROM T_CLIENT JOIN T_TELEPHONE ON T_CLIENT.CLI_ID=T_TELEPHONE.CLI_ID"

## Question 8
Q8_req = "SELECT CLI_NOM,CLI_PRENOM FROM T_CLIENT JOIN(SELECT CLI_NOM as nom,COUNT(CLI_NOM) as nbnom FROM T_CLIENT GROUP BY CLI_NOM)ON T_CLIENT.CLI_NOM=nom  WHERE nbnom>1"

## Question 9
Q9_req = "SELECT CLI_NOM,nbnom FROM (SELECT CLI_NOM,COUNT(CLI_NOM) as nbnom FROM T_CLIENT GROUP BY CLI_NOM) WHERE nbnom>1"
Q9_res = "2"

## Question 10
Q10_req = "SELECT AVG (LIF_REMISE_POURCENT),AVG(LIF_REMISE_MONTANT)  FROM T_LIGNE_FACTURE"
Q10_res = "remis 52, montant 86"

## Question 11
Q11_req = "SELECT MAX (LIF_REMISE_POURCENT),MAX(LIF_REMISE_MONTANT)  FROM T_LIGNE_FACTURE"
Q11_res = "remis 52, montant 86"

## Question 12
Q12_req = "SELECT FAC_ID as fac_id1 FROM T_LIGNE_FACTURE WHERE LIF_REMISE_MONTANT NOT NULL OR LIF_REMISE_POURCENT NOT NULL"


## Question 13
Q13_req = "SELECT DISTINCT CLI_ID FROM T_FACTURE JOIN (SELECT FAC_ID as fac_id1 FROM T_LIGNE_FACTURE WHERE LIF_REMISE_MONTANT NOT NULL OR LIF_REMISE_POURCENT NOT NULL) ON T_FACTURE.FAC_ID=fac_id1"

## Question 14
Q14_req = "SELECT CLI_ID FROM T_CLIENT EXCEPT SELECT DISTINCT CLI_ID FROM T_FACTURE JOIN (SELECT FAC_ID as fac_id1 FROM T_LIGNE_FACTURE WHERE LIF_REMISE_MONTANT NOT NULL OR LIF_REMISE_POURCENT NOT NULL) ON T_FACTURE.FAC_ID=fac_id1"


## Question 15
Q15_req = ""
Q15_res ="GARREAU,Paul,montant"
