NOM = "CLAUSSE"
Prenom = "Agathe"
Classe = "MPSI2"
alpha="41"

## Question 1
Q1_req = "SELECT T_CLIENT.CLI_NOM as nom, T_CLIENT.CLI_PRENOM as prenom, T_TITRE.TIT_LIBELLE as titre FROM T_CLIENT JOIN T_TITRE ON T_CLIENT.TIT_CODE = T_TITRE.TIT_CODE "

## Question 2
Q2_req = "SELECT COUNT (*) as nb_client FROM T_CLIENT"
Q2_res = "93"

## Question 3
Q3_req = "SELECT T_CLIENT.CLI_NOM as nom, T_CLIENT.CLI_PRENOM as prenom FROM T_CLIENT  JOIN T_TITRE ON T_CLIENT.TIT_CODE = T_TITRE.TIT_CODE WHERE T_TITRE.TIT_LIBELLE = "Madame""

## Question 4
Q4_req = "SELECT T_CLIENT.CLI_NOM as nom, T_CLIENT.CLI_PRENOM as prenom, T_TITRE.TIT_LIBELLE as titre FROM T_CLIENT  JOIN T_TITRE ON T_CLIENT.TIT_CODE = T_TITRE.TIT_CODE WHERE T_TITRE.TIT_LIBELLE = "Madame" or T_TITRE.TIT_LIBELLE = "Mademoiselle""


## Question 5
Q5_req = "SELECT count (*) as nb_cliente FROM T_CLIENT JOIN T_TITRE ON T_CLIENT.TIT_CODE = T_TITRE.TIT_CODE WHERE T_TITRE.TIT_LIBELLE = "Madame" or T_TITRE.TIT_LIBELLE = "Mademoiselle""
Q5_res = "16"

## Question 6
Q6_req = "SELECT T_CLIENT.CLI_NOM as Noms, T_CLIENT.CLI_PRENOM as Prénoms FROM T_CLIENT JOIN T_TITRE ON T_CLIENT.TIT_CODE = T_TITRE.TIT_CODE WHERE T_TITRE.TIT_LIBELLE = "Madame" or T_TITRE.TIT_LIBELLE = "Mademoiselle" ORDER BY Noms ASC, Prénoms ASC"


## Question 7
Q7_req = "SELECT T_CLIENT.CLI_NOM as nom, T_CLIENT.CLI_PRENOM as prenom, T_TELEPHONE.TEL_NUMERO as numéro FROM T_CLIENT JOIN T_TELEPHONE ON T_CLIENT.CLI_ID = T_TELEPHONE.CLI_ID"

## Question 8
Q8_req = ""

## Question 9
Q9_req = ""
Q9_res = ""

## Question 10
Q10_req = "SELECT AVG(T_LIGNE_FACTURE.LIF_REMISE_POURCENT) as pourcent, AVG(T_LIGNE_FACTURE.LIF_REMISE_MONTANT) as montant FROM T_LIGNE_FACTURE"
Q10_res = "56% et 90"

## Question 11
Q11_req = "SELECT max(T_LIGNE_FACTURE.LIF_REMISE_POURCENT) as pourcent, max(T_LIGNE_FACTURE.LIF_REMISE_MONTANT) as montant FROM T_LIGNE_FACTURE"
Q11_res = "56% et 90"

## Question 12
Q12_req = "SELECT T_LIGNE_FACTURE.FAC_ID as fac_id1 FROM T_LIGNE_FACTURE WHERE T_LIGNE_FACTURE.LIF_REMISE_MONTANT > 0 or T_LIGNE_FACTURE.LIF_REMISE_POURCENT > 0
"


## Question 13
Q13_req = "SELECT DISTINCT T_FACTURE.CLI_ID FROM T_LIGNE_FACTURE JOIN T_FACTURE ON T_LIGNE_FACTURE.FAC_ID = T_FACTURE.FAC_ID WHERE T_LIGNE_FACTURE.LIF_REMISE_MONTANT > 0 or T_LIGNE_FACTURE.LIF_REMISE_POURCENT > 0
"

## Question 14
Q14_req = "SELECT DISTINCT T_FACTURE.CLI_ID FROM T_LIGNE_FACTURE JOIN T_FACTURE ON T_LIGNE_FACTURE.FAC_ID = T_FACTURE.FAC_ID WHERE T_LIGNE_FACTURE.LIF_REMISE_MONTANT is NULL AND T_LIGNE_FACTURE.LIF_REMISE_POURCENT is NULL"


## Question 15
Q15_req = "SELECT T_FACTURE.CLI_ID, count (*) as nb FROM T_LIGNE_FACTURE, T_FACTURE WHERE T_LIGNE_FACTURE.FAC_ID = T_FACTURE.FAC_ID GROUP BY T_FACTURE.CLI_ID ORDER BY nb DESC LIMIT 1

SELECT T_CLIENT.CLI_NOM, T_CLIENT.CLI_PRENOM FROM T_CLIENT WHERE T_CLIENT.CLI_ID = 18

SELECT SUM( T_LIGNE_FACTURE.LIF_REMISE_MONTANT) FROM T_LIGNE_FACTURE WHERE T_LIGNE_FACTURE.FAC_ID = (SELECT T_FACTURE.FAC_ID FROM T_FACTURE WHERE T_FACTURE.CLI_ID = 18 )"
Q15_res ="fayolle,olivier,montant"
