NOM = "Espinoza"
Prenom = "Walter"
Classe = "MPSI2"
alpha="62"

## Question 1
Q1_req = "SELECT TIT_CODE,CLI_NOM,CLI_PRENOM FROM T_CLIENT"

## Question 2
Q2_req = "SELECT count(*) FROM T_CLIENT"
Q2_res = "89"

## Question 3
Q3_req = "SELECT CLI_NOM, CLI_PRENOM from T_CLIENT WHERE TIT_CODE = 'Mme.'"


## Question 4
Q4_req = "SELECT CLI_NOM, CLI_PRENOM, TIT_CODE from T_CLIENT WHERE TIT_CODE != 'M.'"


## Question 5
Q5_req = "SELECT count(*) FROM (SELECT TIT_CODE, CLI_PRENOM from T_CLIENT WHERE TIT_CODE != 'M.')"
Q5_res = "16"

## Question 6
Q6_req = "SELECT CLI_NOM as Noms, CLI_PRENOM as Prenoms from T_CLIENT WHERE TIT_CODE != 'M.' ORDER by Noms "


## Question 7
Q7_req = "SELECT CLI_NOM AS Nom, TEL_NUMERO AS Téléphone FROM T_CLIENT, T_TELEPHONE WHERE T_CLIENT.CLI_ID=T_TELEPHONE.CLI_ID ORDER BY CLI_NOM "

## Question 8
Q8_req = "SELECT T_CLIENT.CLI_NOM, T_CLIENT.CLI_PRENOM FROM T_CLIENT WHERE T_CLIENT.CLI_NOM = (SELECT T_CLIENT.CLI_NOM FROM T_CLIENT GROUP by T_CLIENT.CLI_NOM HAVING  count(CLI_NOM)>1)"

## Question 9
Q9_req = "SELECT T_CLIENT.CLI_NOM, count(CLI_NOM) FROM T_CLIENT WHERE T_CLIENT.CLI_NOM = (SELECT T_CLIENT.CLI_NOM FROM T_CLIENT GROUP by T_CLIENT.CLI_NOM HAVING count(CLI_NOM)>1)"
Q9_res = "3"

## Question 10
Q10_req = "SELECT avg(LIF_REMISE_MONTANT) ,avg(LIF_REMISE_POURCENT) from T_LIGNE_FACTURE"
Q10_res = "111.0 | 77.0"

## Question 11
Q11_req = "SELECT max(LIF_REMISE_MONTANT) ,max(LIF_REMISE_POURCENT) from T_LIGNE_FACTURE"
Q11_res = "111 | 77"

## Question 12
Q12_req = "SELECT FAC_ID AS fac_id1 FROM T_LIGNE_FACTURE WHERE LIF_REMISE_MONTANT>0 OR LIF_REMISE_POURCENT>0"


## Question 13
Q13_req = "SELECT CLI_ID FROM T_LIGNE_FACTURE,T_CLIENT WHERE LIF_REMISE_MONTANT>0 OR LIF_REMISE_POURCENT>0 AND T_CLIENT.CLI_ID = T_LIGNE_FACTURE.FAC_ID"

## Question 14
Q14_req = "SELECT CLI_ID FROM T_LIGNE_FACTURE,T_CLIENT WHERE LIF_REMISE_MONTANT is NULL OR LIF_REMISE_POURCENT is NULL AND T_CLIENT.CLI_ID = T_LIGNE_FACTURE.FAC_ID"


## Question 15
Q15_req = "SELECT CLI_NOM as 'Nom', CLI_PRENOM as 'Prénom' FROM T_LIGNE_FACTURE,T_CLIENT WHERE LIF_REMISE_MONTANT = (SELECT max(lif_remise_montant) FROM T_LIGNE_FACTURE) AND LIF_REMISE_POURCENT =( SELECT max(lif_remise_pourcent) FROM T_LIGNE_FACTURE) and T_CLIENT.CLI_ID = T_LIGNE_FACTURE.FAC_ID"
Q15_res ="nom,prenom,montant"
